[env:esp32-s3-wrover]
platform = espressif32 @ 6.5.0   ; <--- THE SILVER BULLET
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps = 
    bodmer/TFT_eSPI @ ^2.5.31

build_flags =
    -DBOARD_HAS_PSRAM
    -D USER_SETUP_LOADED=1
    -D ILI9341_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MOSI=11      ; Native S3 pin
    -D TFT_SCLK=12      ; Native S3 pin
    -D TFT_CS=10        ; Native S3 pin
    -D TFT_MISO=13      ; Native S3 pin
    -D TFT_DC=4         ; Safe GPIO
    -D TFT_RST=5        ; Safe GPIO
    -D LOAD_GLCD=1
    -D SPI_FREQUENCY=40000000